/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_helloworld_NDK */

#ifndef _Included_com_example_administrator_helloworld_NDK
#define _Included_com_example_administrator_helloworld_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_helloworld_NDK
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_helloworld_NDK_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_example_administrator_helloworld_NDK
 * Method:    getString_From_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_helloworld_NDK_getString_1From_1c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
